"""
XGBoost QED scheduler training (§4.2).

Trains two gradient-boosted tree regressors:
  - M_delta_S : predicts success uplift  Delta_S
  - M_R       : predicts post-selection retention R

Training data: 50,000 circuit-noise pairs generated by cuQuantum simulation.
5-fold cross-validation is used for hyperparameter validation.
"""

from __future__ import annotations

import pickle
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import r2_score

try:
    import xgboost as xgb
    _HAS_XGB = True
except ImportError:
    _HAS_XGB = False
    import warnings
    warnings.warn("XGBoost not found; install xgboost>=2.0 for scheduler training.")


class QEDSchedulerTrainer:
    """Train the pair of XGBoost regressors for the QED scheduler.

    Parameters
    ----------
    n_estimators : int
        Number of boosting rounds (paper: 500).
    learning_rate : float
        Step-size shrinkage (paper: 0.05).
    max_depth : int
        Maximum tree depth (paper: 6).
    subsample : float
        Row-sampling ratio per tree.
    colsample_bytree : float
        Column-sampling ratio per tree.
    seed : int
        Random seed for reproducibility.
    """

    def __init__(
        self,
        n_estimators: int = 500,
        learning_rate: float = 0.05,
        max_depth: int = 6,
        subsample: float = 0.8,
        colsample_bytree: float = 0.8,
        seed: int = 42,
    ) -> None:
        if not _HAS_XGB:
            raise ImportError("xgboost is required for QEDSchedulerTrainer.")

        self.params = dict(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            subsample=subsample,
            colsample_bytree=colsample_bytree,
            random_state=seed,
            tree_method="hist",
            eval_metric="rmse",
        )
        self.model_delta_s: Optional[xgb.XGBRegressor] = None
        self.model_R: Optional[xgb.XGBRegressor] = None
        self.cv_scores_delta_s: Optional[np.ndarray] = None
        self.cv_scores_R: Optional[np.ndarray] = None

    # ------------------------------------------------------------------

    def load_data(
        self,
        features_path: str,
        labels_path: str,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Load training features and labels from CSV files.

        Parameters
        ----------
        features_path : str
            Path to ``features.csv`` (columns: feature names).
        labels_path : str
            Path to ``labels.csv`` (columns: ``delta_s``, ``retention``).

        Returns
        -------
        X : np.ndarray, shape (n_samples, 8)
            Feature matrix (6 circuit features + syndrome frequency f +
            block insertion position p, one-hot encoded to a scalar).
        y_delta_s : np.ndarray, shape (n_samples,)
        y_R : np.ndarray, shape (n_samples,)
        """
        X_df = pd.read_csv(features_path)
        y_df = pd.read_csv(labels_path)

        X = X_df.values.astype(np.float64)
        y_delta_s = y_df["delta_s"].values.astype(np.float64)
        y_R = y_df["retention"].values.astype(np.float64)
        return X, y_delta_s, y_R

    def train(
        self,
        X_train: np.ndarray,
        y_delta_s_train: np.ndarray,
        y_R_train: np.ndarray,
        n_folds: int = 5,
    ) -> Dict[str, float]:
        """Fit both regressors with 5-fold cross-validation.

        Returns
        -------
        dict
            ``{'mean_r2_delta_s': float, 'mean_r2_R': float}``.
        """
        kf = KFold(n_splits=n_folds, shuffle=True, random_state=42)

        # --- M_delta_S ---
        self.model_delta_s = xgb.XGBRegressor(**self.params)
        self.cv_scores_delta_s = cross_val_score(
            self.model_delta_s, X_train, y_delta_s_train,
            cv=kf, scoring="r2",
        )
        self.model_delta_s.fit(X_train, y_delta_s_train)

        # --- M_R ---
        self.model_R = xgb.XGBRegressor(**self.params)
        self.cv_scores_R = cross_val_score(
            self.model_R, X_train, y_R_train,
            cv=kf, scoring="r2",
        )
        self.model_R.fit(X_train, y_R_train)

        return {
            "mean_r2_delta_s": float(np.mean(self.cv_scores_delta_s)),
            "mean_r2_R": float(np.mean(self.cv_scores_R)),
        }

    def evaluate(
        self,
        X_test: np.ndarray,
        y_delta_s_test: np.ndarray,
        y_R_test: np.ndarray,
    ) -> Dict[str, float]:
        """Compute held-out R² scores on a test split."""
        if self.model_delta_s is None or self.model_R is None:
            raise RuntimeError("Call train() before evaluate().")

        r2_ds = r2_score(y_delta_s_test, self.model_delta_s.predict(X_test))
        r2_r = r2_score(y_R_test, self.model_R.predict(X_test))
        return {"r2_delta_s": r2_ds, "r2_R": r2_r}

    def save(self, checkpoint_path: str) -> None:
        """Serialise both models to a single pickle checkpoint."""
        payload = {
            "model_delta_s": self.model_delta_s,
            "model_R": self.model_R,
            "cv_scores_delta_s": self.cv_scores_delta_s,
            "cv_scores_R": self.cv_scores_R,
            "params": self.params,
        }
        Path(checkpoint_path).parent.mkdir(parents=True, exist_ok=True)
        with open(checkpoint_path, "wb") as fh:
            pickle.dump(payload, fh, protocol=pickle.HIGHEST_PROTOCOL)

    @classmethod
    def load(cls, checkpoint_path: str) -> "QEDSchedulerTrainer":
        """Load a previously saved checkpoint."""
        with open(checkpoint_path, "rb") as fh:
            payload = pickle.load(fh)
        trainer = cls.__new__(cls)
        trainer.__dict__.update(payload["params"])
        trainer.model_delta_s = payload["model_delta_s"]
        trainer.model_R = payload["model_R"]
        trainer.cv_scores_delta_s = payload.get("cv_scores_delta_s")
        trainer.cv_scores_R = payload.get("cv_scores_R")
        trainer.params = payload["params"]
        return trainer
